# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Author:
    id: int
    name: str
    bio: str


@dataclasses.dataclass()
class User:
    id: int
    email: str
    name: str
    bio: Optional[str]
    age: Optional[int]
    active: Optional[bool]
    created_at: datetime.datetime
